### ISSUE TITLE
Complete Payments GUI

### ISSUE THREAD

**Issue by vycos-zen** [peterkollerlv/LoanLifeTracker#1]
Needs to reflect payment amount, trackbar value, interest payment, and principal payment interactively.

**Comment by vycos-zen** [comment]
Completed the gui logic, needs % display of the allocation

**Comment by peterkollerlv** [comment]
COmpleted the % display of the payment allocation

**Comment by vycos-zen** [comment]
Completed the % display of the payment allocation
